### ISSUE TITLE
[BUG] - USER CAN CREATE MULTIPLE VM

### ISSUE THREAD

**Issue by Droidkaz** [vultr/whmcs-vultr#62] opened 2020-01-05 06:11 UTC
Hi , i found this bug on my whmcs

1. After USER placing an order, ADMIN accept & mark to paid. But ADMIN can't create product / VM.
2. After ADMIN accept an order, USER (my dummy user) can create VM multiple times (connect to Vultr). But there are no VM details in whmcs. See at attachment, button to CREATE vm still active after create a VM. So i can create VM again & again.
3. After all, no email comes to the user after the VM has been installed.

**Screenshots**
![WHMCS USER SCR](https://user-images.githubusercontent.com/59523449/71775931-0c4d3e00-2fbb-11ea-94de-b2af78751f01.jpg)

 - Browser Opera
 - WHMCS 7.8.3
 - PHP 7.2 (ea-php72)
 - Module v2.04
 - i've Enable API to all IPv4 & IPv6 to make sure my server can connect
 - i've read Vultr guide to install, it's very clear

**Comment by eran101** [comment] 2020-01-05 10:39
> 2\. After ADMIN accept an order, USER (my dummy user) can create VM multiple times (connect to Vultr). But there are no VM details in whmcs. See at attachment, button to CREATE vm still active after create a VM. So i can create VM again & again.

I have this bug too and Vultr closed the issue:
https://github.com/vultr/whmcs-vultr/issues/59

**Comment by ddymko** [comment] 2020-01-05 14:16
I am going to close this ticket out since it is a duplicate of #59 which has been reopened

**Closed by ddymko** 2020-01-05 14:16 UTC
Labels: bug
